version: '3.8'
services:
  pgsql:
    container_name: pgsql
    image: postgres:14.1-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./pgsql:/var/lib/postgresql/data
  # backend:
  #   container_name: node_server
  #   build:
  #     context: ./server
  #   volumes:
  #     - ./server:/app
  #   ports:
  #     - '3001:3001'
  #   depends_on:
  #     - pgsql
  # vue-client:
  #   container_name: vue_client
  #   build:
  #     context: ./client
  #   volumes:
  #     - ./client:/app
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - backend
  # db-migrator:
  #   container_name: db_migrator
  #   build:
  #     context: ./migrator
  #   depends_on:
  #     - pgsql
  #   environment:
  #     - DATABASE_URL=postgres://postgres:postgres@pgsql:5432/yourdbname